defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      #default values for meta tags. can be configured per page in each template
      title: "JBCNConf - The first Java and JVM conference in Spain"
      description: "The first big Java and JVM conference in Spain. Barcelona will host this great event next 27th to 29th of May 2019. 3 days to share knowledge and experiences, to meet enthusiasts and geeks, and to learn about new technologies."
      keywords: "java barcelona, jug barcelona, jbcnconf, java barcelona conference"
layouts_dir: 2019/_layouts
includes_dir: 2019/_includes
data_dir: 2019/_data
exclude: ["vendor","README.*","/tools/**", "Gemfile", "Rakefile"]
